### PR TITLE
Update index.html #Added_footer_feature 

### PR DESCRIPTION
**Pull request by saikatdgp2001**
added the footer feature

### CODE REVIEW

**Comment by saikatdgp2001** [comment]
Plz accept it with proper Hacktoberfest tags

**Comment by saikatdgp2001** [comment]
Plz review the changes and merge it with proper Hacktoberfest tags.

**Comment by saikatdgp2001** [comment]
please check the changes, and give merge them with the repo.

**Comment by ankitmalakar7** [comment]
Already checked those changes and it was not needed. If you have contributed once, you are already done.

**Pull request closed without merging**
